---
-
  hosts: all

  vars:
    user: vagrant

  tasks:
    -
      name: apt-get update
      apt: update_cache=yes cache_valid_time=360000
      sudo: true

    -
      name: Install packages
      apt: pkg={{ item }} state=installed
      sudo: true
      with_items:
        - vim

    -
      include: tasks/java.yml

    -
      include: tasks/ant.yml

    -
      include: tasks/android-sdk.yml
      vars:
        android:
          version: x86_64-20140702
          filename: adt-bundle-linux-x86_64-20140702
          path: ~/Programs/adt-bundle-linux-x86_64-20140702
        downloadsFolder: ~/Downloads/

    -
      include: tasks/nvm.yml

    -
      { include: tasks/node.yml, node: { version: 0.11.13, setDefault: false } }

    -
      { include: tasks/node.yml, node: { version: 0.10.29, setDefault: true } }

    -
      include: tasks/npm.yml

    -
      include: tasks/gulp.yml

    -
      include: tasks/rvm.yml

    -
      { include: tasks/ruby.yml, ruby: { version: 2.1.2 }}

    -
      include: tasks/gems.yml

    -
      include: tasks/gems.yml
