-
  name: Download android SDK
  shell: wget -P {{ downloadsFolder }} http://dl.google.com/android/adt/adt-bundle-linux-{{ android.version }}.zip

-
  name: Unzip android SDK
  shell: unzip {{ downloadsFolder }}{{ android.filename }}.zip -d ~/Programs

-
  name: Change owner for android SDK
  shell: chown -R {{ user }} {{ android.path }}
  sudo: true

-
  name: Add android path to bashrc
  shell: echo "\n# Android SDK\nPATH=\$PATH:{{ android.path }}/sdk/platform-tools:{{ android.path }}/sdk/tools" >> ~/.bashrc
