---
-
  hosts: all

  tasks:
    -
      name: apt-get update
      apt: update_cache=yes cache_valid_time=360000
      sudo: true
    -
      name: Install ant
      apt: pkg=ant update_cache=yes state=installed
