-
  name: Add java repositories
  sudo: true
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

-
  name: Shell accepted oracal license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

-
  name: Install java7
  apt: pkg=oracle-java7-installer update_cache=yes state=installed
